apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pingservice-pr-ace
spec:
  pipelineRef:
    name: pipeline-ace
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  params:
    - name: repo-url
      value: https://github.com/andreas-bradahl/ping-service-demo-app.git
    - name: registry-url
      value: image-registry.openshift-image-registry.svc:5000