apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: petstore-pr
spec:
  pipelineRef:
    name: pipeline-ace
  params:
  - name: event-repo
    value: 'https://github.com/andreasbradahl-avella/petstore.git'
  - name: build-scripts-repo
    value: 'https://github.com/andreasbradahl-avella/ace-pipelines-build-repo.git'
  - name: github-topic
    value: petstore
  - name: github-user
    value: andreasbradahl-avella
  # - name: application-name
  #   value: 'petstore'
  # - name: commit-id
  #   value: 'this1is2a3mocked4commit5id'
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "managed-premium"
          resources:
            requests:
              storage: 1Gi