apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tip-tip001-pr
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: pipeline-ace
  params:
  - name: event-repo-name
    value: tip001-ace-lervig-java
  - name: github-user
    value: tineikt
  - name: github-branch
    value: cicd
  - name: commit-id
    value: 4327edc
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "managed-premium"
          resources:
            requests:
              storage: 1Gi