apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tip-dsp-pr
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: pipeline-ace
  params:
  - name: event-repo-name
    value: tip004-ace-assortements-rest
  - name: github-user
    value: tineikt
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "managed-premium"
          resources:
            requests:
              storage: 1Gi