apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fetch-multiple-repos
spec:
  params:
    - name: topic
  steps:
    - name: curl-repos-topic
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli
      script: |
        echo "Fetch repositories with topic '$(params.topic)'."
        
        
