apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clean-up
spec:
  params:
    - name: application-name
  steps:
    - name: delete-test-environment
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli
      command:
        - oc
        - delete
        - integrationserver.appconnect.ibm.com/$(params.application-name)-test