apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: inspect
spec:
  workspaces:
    - name: source
  params:
    - name: path
  steps:
    - name: find-workspace
      image: ubuntu
      command:
      - /bin/bash
      args:
      - -c
      - |
        set -ex
        find $(params.path)
        cat /workspace/source/repos/repos.json