apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-e2e-tests
spec:
  params:
    - name: application-name
  workspaces:
    - name: source
  steps:
    - name: run-soapui-tests
      image: openjdk:11
      securityContext:
        privileged: true
        runAsUser: 0
      script: |
        curl https://s3.amazonaws.com/downloads.eviware/soapuios/5.6.0/SoapUI-5.6.0-linux-bin.tar.gz --output SoapUI-5.6.0-linux-bin.tar.gz
        tar -xzf SoapUI-5.6.0-linux-bin.tar.gz -C /opt/
        rm /opt/SoapUI-5.6.0/lib/xmlbeans-xmlpublic-2.6.0.jar
        /opt/SoapUI-5.6.0/bin/testrunner.sh -r /workspace/source/tests/$(params.application-name)-tests-soapui-project.xml
