apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-build-bar
spec:
  steps:
    - name: create-buildconfig
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      script: |
        echo "Creating BuildConfig manifest"
        cat << EOF > ace-buildconfig.yaml
        apiVersion: build.openshift.io/v1
        kind: BuildConfig
        metadata:
          name: pingserver-app
          namespace: cicd-pingserver
        spec:
          source:
            git:
              uri: https://github.com/andreas-bradahl/ping-service-demo-app.git
              ref: main
            # contextDir: "source/PingService"
            dockerfile: |
              FROM ibmcom/ace-server:latest
              COPY source/PingService /home/aceuser/PingService
              RUN export LICENSE="accept"
                && source /opt/ibm/ace-11/server/bin/mqsiprofile
                && mkdir /home/aceuser/bars
                && mqsipackagebar -a bars/PingService.bar -k PingService
                && mqsibar -a bars/PingService.bar -w /home/aceuser/ace-server
                && chmod -R 777 /home/aceuser/ace-server/run/PingService
            strategy:
              type: Docker
            output:
              to:
                kind: ImageStreamTag
                name: ping-service:latest
        EOF
        echo "Applying BuildConfig manifest to OpenShift cluster"
        oc apply -f ace-buildconfig.yaml
