apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ace-github-eventlistener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: ace-github-trigger
      interceptors:
        - github:
            # secretRef:
            #   secretName: ace-github-secret
            #   # secretKey: secretToken
            eventTypes:
              - push
      bindings:
        - ref: ace-github-binding
      template:
        name: ace-github-template