apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ace-github-template
spec:
  params:
  - name: git-repo-url
  - name: git-repo-name
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: $(tt.params.git-repo-name)-github-event-
    spec:
      pipelineRef:
        name: pipeline-ace
      params:
      - name: repo-url
        value: $(tt.params.git-repo-url)
      - name: release-name
        value: $(tt.params.git-repo-name)
      workspaces:
        - name: shared-data
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi