apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: my-amazing-integration-server
spec:
  version: 11.0.0
  pod:
    containers:
      runtime:
        image: image-registry.openshift-image-registry.svc:5000/cicd-experimental/
      license:
        accept: true
        license: L-APEH-BSVCHU
        use: CloudPakForIntegrationNonProduction
      barURL: ’’
      designerFlowsOperationMode: disabled
      service:
    endpointType: http
useCommonServices: false
replicas: 1