apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-ace
spec:
  description: |
    Simple pipeline to demonstrate ACE build on OpenShift
    pipelines.
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
  - name: branch-name
    type: string
    description: The git branch to clone.
  - name: registry-url
    type: string
    description: The hostname of the image registry to be used
  workspaces:
  - name: shared-data
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task for the commit to be checked.
  tasks:
    # Task 1: Clone git repository to workspace
    - name: fetch-repo
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
      - name: output
        workspace: shared-data
      params:
      - name: url
        value: $(params.repo-url)
    # Task 2: Run code level tests, continuous inspection etc.
    # Task 3: Build ACE image and push to OCP registry
    - name: build-ace-image
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - fetch-repo
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: IMAGE
          value: $(params.registry-url)/$(context.pipelineRun.namespace)/$(context.pipelineRun.name)
        - name: TLSVERIFY
          value: 'false'
    # Task 4: Create and deploy IntegrationServer manifest
    - name: deploy-integration-server
      taskRef:
        name: create-and-deploy-integration-server
      runAfter:
        - build-ace-image
      params:
        - name: IMAGE
          value: $(params.registry-url)/$(context.pipelineRun.namespace)/$(context.pipelineRun.name)
 