apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-ace
spec:
  description: |
    Simple pipeline to demonstrate ACE build on OpenShift
    pipelines.
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
  - name: branch-name
    type: string
    description: The git branch to clone.
  workspaces:
  - name: shared-data
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task for the commit to be checked.
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
      - name: output
        workspace: shared-data
      params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.branch-name)
    # - name: show-tree
    #   taskRef:
    #     name: display-tree
    #   workspaces:
    #     - name: git-source
    #       workspace: shared-data
    #   runAfter:
    #     - fetch-repo
    - name: build-image
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - fetch-repo
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(context.pipelineRun.name)
        - name: TLSVERIFY
          value: 'false'
