apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-dip
spec:
  description: |
    Simple pipeline to demonstrate ACE build on DIP.
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
  - name: application-name
    type: string
    description: The name of the application
  workspaces:
  - name: shared-data
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task for the commit to be checked.
  tasks:
    # Task 1: Clone git repository to workspace
    - name: fetch-repo
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
      - name: output
        workspace: shared-data
      params:
      - name: url
        value: $(params.repo-url)
    - name: inspect-file-structure
      taskRef:
        name: inspect
      runAfter:
        - fetch-repo
    # Task 2: Build BAR
    - name: build-bar
      taskRef:
        name: build-bar
      runAfter:
        - fetch-repo
      workspaces:
      - name: cloned-repo
        workspace: shared-data
      params:
      - name: application-name
        value: $(params.application-name)
    # Debugging task
    - name: inspect-file-structure
      taskRef:
        name: inspect
      runAfter:
        - fetch-repo
    # Task 3: Push deployment artifacts to Satellite repo
    - name: push-artifacts
      taskRef:
        name: push-artifacts
      runAfter:
        - build-bar
      workspaces:
      - name: cloned-repo
        workspace: shared-data
      params:
      - name: application-name
        value: $(params.application-name)
    # Task 4: Trigger Ansible playbook
    - name: trigger-ansible-deploy
      taskRef:
        name: trigger-ansible-deploy
      runAfter:
        - push-artifacts
      workspaces:
      - name: cloned-repo
        workspace: shared-data
      params:
      - name: application-name
        value: $(params.application-name)
    # Debugging task
    - name: inspect-file-structure
      taskRef:
        name: inspect
      runAfter:
        - fetch-repo    