apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-ace
spec:
  description: |
    Simple pipeline to demonstrate ACE build on OpenShift
    pipelines.
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
  - name: release-name
    type: string
    description: The release name of the application
  - name: commit-id
    type: string
    description: The commit hash identifier for the current HEAD commit
  workspaces:
  - name: shared-data
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task for the commit to be checked.
  tasks:
    # Task 1: Clone git repository to workspace
    - name: fetch-repo
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
      - name: output
        workspace: shared-data
      params:
      - name: url
        value: $(params.repo-url)
    # Task 2: Run code level tests, continuous inspection etc.
    # Task 3: Build ACE image and push to OCP registry
    - name: build-ace-image
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - fetch-repo
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.release-name)-$(params.commit-id)
        - name: TLSVERIFY
          value: 'false'
    # Task 4: Create and deploy IntegrationServer manifest
    - name: deploy-to-test
      taskRef:
        name: create-and-deploy-integration-server
      runAfter:
        - build-ace-image
      params:
        - name: release-name
          value: $(params.release-name)-test
        - name: image-name
          value: $(params.release-name)
        - name: namespace
          value: $(context.pipelineRun.namespace)
        - name: commit-id
          value: $(params.commit-id)
    # Task 5: Run SoapUI tests against deployed route
    - name: run-e2e-tests
      taskRef:
        name: run-e2e-tests
      runAfter:
        - deploy-to-test
      workspaces:
        - name: source
          workspace: shared-data
    # Task 6: Deploy to production environment
    - name: deploy-to-prod
      taskRef:
        name: create-and-deploy-integration-server
      runAfter:
        - run-e2e-tests
      params:
        - name: release-name
          value: $(params.release-name)-prod
        - name: image-name
          value: $(params.release-name)
        - name: namespace
          value: $(context.pipelineRun.namespace)
        - name: commit-id
          value: $(params.commit-id)
  finally:
    # Task 7: Clean up
    - name: clean-up
      taskRef:
        name: clean-up
      params:
        - name: release-name
          value: $(params.release-name)