apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-artifacts
spec:
  params:
    - name: scripts-dir
    - name: repo-list
    - name: commands-file
      default: "mqsipackagebar_commands.txt"
    - name: projects-workspace
      default: "projects_workspace"
    - name: pod-name
  workspaces:
    - name: sources
  stepTemplate:
    name: build-artifacts-step-template
    image: image-registry.openshift-image-registry.svc:5000/cicd/ubi8-tip
    workingDir: /workspace/sources
  steps:

    - name: gather-all-project-directories
      script: |
        #!/bin/bash

        cd common-workspace
        . ../$(params.scripts-dir)/move_projects_to_common_workspace.sh ../$(params.projects-workspace) projects
        
        # TODO: For debug purposes - remove when appropriate
        find /workspace/sources/projects_workspace

    - name: build-mqsipackagebar-commands
      script: |
        #!/bin/bash

        # Add only the app (not libs) folders to the package command
        touch $(params.commands-file)

        ./$(params.scripts-dir)/build_mqsipackagebar_commands.sh $(params.repo-list) $(params.projects-workspace) $(params.commands-file)

    - name: build-bar-files
    # TODO: find the correct ACE image to use
      image: icr.io/appc-dev/ace-server@sha256:980a561ba72fcc53f46e909f9f94c521aa66bf11a3e286480c8074d4e8bb40fe
      securityContext:
        privileged: true
        runAsUser: 0
      script: |
        #!/bin/bash

        set -eu

        mkdir -p bars

        cd $(params.projects-workspace)

        while IFS= read line; do
          $line
        done < ../$(params.commands-file)

        # TODO: For debug purposes - remove when appropriate
        find /workspace/sources/bars

    - name: apply-qa-overrides
    # TODO: find the correct ACE image to use
      image: icr.io/appc-dev/ace-server@sha256:980a561ba72fcc53f46e909f9f94c521aa66bf11a3e286480c8074d4e8bb40fe
      securityContext:
        privileged: true
        runAsUser: 0
      script: |
        #!/bin/bash

        set -eu

        # For each BAR file, apply BAR override
        for bar in bars/*.bar; do
          REPO_NAME=$(basename "${bar%.*}")
          PROPERTIES_FILE="common-workspace/${REPO_NAME}/config/qa/overrides/${REPO_NAME}.qa.properties"

          echo "BAR file: $bar"
          echo "Repo name: $REPO_NAME"
          echo "Properties file: $PROPERTIES_FILE"

          mqsiapplybaroverride -b "$bar" -p "$PROPERTIES_FILE" -r

        done


    - name: create-inline-dockerfile
      script: |
        #!/bin/bash

        cat << 'EOF' > Dockerfile
        FROM icr.io/appc-dev/ace-server@sha256:980a561ba72fcc53f46e909f9f94c521aa66bf11a3e286480c8074d4e8bb40fe
        ENV LICENSE accept
        RUN mkdir -p /home/aceuser/initial-config/bars
        COPY bars/*.bar /home/aceuser/initial-config/bars
        EOF

        cat Dockerfile
        
    - name: build-image
      image: quay.io/buildah/stable
      volumeMounts:
      - name: varlibc
        mountPath: /var/lib/containers
      securityContext:
        privileged: true
        runAsUser: 0
      script: |
        #!/bin/bash

        buildah \
        bud \
        --tls-verify=false \
        --layers \
        -f ./Dockerfile \
        -t image-registry.openshift-image-registry.svc:5000/cicd/$(params.pod-name) 

    - name: push-image
      image: quay.io/buildah/stable
      volumeMounts:
      - name: varlibc
        mountPath: /var/lib/containers
      securityContext:
        privileged: true
        runAsUser: 0
      script: |
        #!/bin/bash

        buildah \
        push \
        --tls-verify=false \
        image-registry.openshift-image-registry.svc:5000/cicd/$(params.pod-name) 

  volumes:
    - name: varlibc
      emptyDir: {}