apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-artifacts
spec:
  params:
    - name: scripts-dir
    - name: repo-list
    - name: commands-file
      default: "mqsipackagebar_commands.txt"
    - name: projects-workspace
      default: "projects_workspace"
  workspaces:
    - name: sources
  stepTemplate:
    name: build-artifacts-step-template
    image: image-registry.openshift-image-registry.svc:5000/cicd/ubi8-tip
    workingDir: /workspace/sources
  steps:

    - name: gather-all-project-directories
      script: |
        #!/bin/bash

        cd common-workspace
        . ../$(params.scripts-dir)/move_projects_to_common_workspace.sh ../$(params.projects-workspace) projects
        
        # TODO: For debug purposes - remove when appropriate
        find /workspace/sources

    - name: build-mqsipackagebar-commands
      script: |
        #!/bin/bash

        # Add only the app (not libs) folders to the package command
        touch $(params.commands-file)

        ./$(params.scripts-dir)/build_mqsipackagebar_commands.sh $(params.repo-list) $(params.projects-workspace) $(params.commands-file)

    - name: build-bar-files
    # TODO: find the correct ACE image to use
      image: icr.io/appc-dev/ace-server@sha256:980a561ba72fcc53f46e909f9f94c521aa66bf11a3e286480c8074d4e8bb40fe
      script: |
        #!/bin/bash

        set -eu

        mkdir -p bars

        cd $(params.projects-workspace)

        while IFS= read line; do
          $line
        done < ../$(params.commands-file)

        # TODO: For debug purposes - remove when appropriate
        find /workspace/sources/bars

    # - name: create-inline-dockerfile
    #   image: image-registry.openshift-image-registry.svc:5000/openshift/cli
    #   securityContext:
    #     privileged: true
    #     runAsUser: 0
    #   workingDir: /workspace/sources
    #   script: |
    #     #!/bin/sh
    #     printf "Creating inline Dockerfile...\n"
    #     cat << 'EOF' > Dockerfile
    #     FROM ibmcom/ace-server:latest
    #     ENV LICENSE accept
    #     RUN mkdir /home/aceuser/bars/
    #     COPY bars/*.bar /home/aceuser/bars/
    #     RUN source /opt/ibm/ace-11/server/bin/mqsiprofile \
    #         && for f in /home/aceuser/bars/*.bar; do mqsibar -a $f -w /home/aceuser/ace-server; done
    #     EOF

    #     cat Dockerfile
    #     pwd