apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-repos
spec:
  params:
    - name: event-repo-name
    - name: github-user
  workspaces:
    - name: sources
  steps:
    - name: get-topic-and-clone-repos
      image: alpine
      securityContext:
        privileged: true
        runAsUser: 0
      workingDir: /workspace/sources
      script: |
        #!/bin/sh

        apk add jq curl git

        echo "Event repo name: $(params.event-repo-name)"
        echo "GitHub user: $(params.github-user)"

        echo "Cloning build scripts repo..."
        git clone https://github.com/$(params.github-user)/ace-pipelines-build-repo.git build-repo
        
        echo "Getting pod bundle topic name from repository..."
        topic="$(build-repo/scripts/get_pod_bundle_topic.sh "$(params.github-user)" "$(params.event-repo-name)")"

        if [ -z "$topic" ]
        then
          echo "No topic with pod bundle name found for this repo. Cloning event repo only..."
          git clone https://github.com/$(params.github-user)/$(params.event-repo-name).git sources/repos/$(params.event-repo-name)
        else
          echo "Getting repositories with same topic..."
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/search/repositories?q=user:$(params.github-user)+topic:$topic" | 
            jq -r '[.items[].name]' > repos_list.json

          echo "Found $(jq length repos_list.json) repos with same bundle topic name."

          jq -cr '.[]' repos_list.json | while read repo; do
              git clone https://github.com/$(params.github-user)/$repo.git sources/repos/$repo
          done
        fi

        find /workspace
    - name: get-dependencies
      image: alpine
      securityContext:
        privileged: true
        runAsUser: 0
      workingDir: /workspace/sources
      script: |
        #!/bin/sh

         
