apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-dependent-repos
spec:
  params:
    - name: github-user
  workspaces:
    - name: sources
  steps:
    - name: clone-each-repo-in-list
      image: quay.io/wire/alpine-git
      securityContext:
        privileged: true
        runAsUser: 0
      script: |
        #!/bin/sh

        apk add jq
        
        inputfile="/workspace/sources/repos/repos.json"

        jq -cr '.[]' $inputfile | while read line; do

          REPO_DIR=./sources/repos/$line/.git

          if [ ! -d $REPO_DIR ]
          then
            echo "Cloning repo '$line'"
            $(git clone https://github.com/$(params.github-user)/$line.git /workspace/sources/repos/$line)
          else
            echo "Repo '$line' already exists."
          fi

        done

        find /workspace