apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-repos
spec:
  params:
    - name: event-repo-name
    - name: github-user
  workspaces:
    - name: sources
  steps:
    - name: get-build-repo
      image: image-registry.openshift-image-registry.svc:5000/cicd/ubi8-tip
      workingDir: /workspace/sources
      script: |
        #!/bin/bash

        echo "Event repo name: $(params.event-repo-name)"
        echo "GitHub user: $(params.github-user)"

        # TODO: build repo needs to be transfered to user:tineikt
        git clone https://github.com/andreasbradahl-avella/ace-pipelines-build-repo.git build-repo
    - name: get-repos-with-this-topic
      image: image-registry.openshift-image-registry.svc:5000/cicd/ubi8-tip
      workingDir: /workspace/sources
      script: |
        #!/bin/bash
        
        echo "Getting pod bundle topic name from repository..."
        TOPIC=$(curl \
          -u tip-github:"$GH_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$(params.github-user)/$(params.event-repo-name) | 
          jq -r '.topics[] | select(. | startswith("pod"))')

        if [ -z "$TOPIC" ]
        then
          echo "No topic with pod bundle name found for this repo. Cloning event repo only..."
          git clone -b cicd https://github.com/$(params.github-user)/$(params.event-repo-name).git common-workspace/$(params.event-repo-name)
        else
          echo "Getting repositories with topic '${TOPIC}'..."

          curl \
            -u tip-github:"$GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/search/repositories?q=user:$(params.github-user)+topic:${TOPIC}" | 
            jq -r '[.items[].name]' > repos_list.json

          echo "Found $(jq length repos_list.json) repos with bundle topic name $TOPIC."

          jq -cr '.[]' repos_list.json | while read repo; do
              python3 build-repo/scripts/fetch_dependencies_recursively.py $repo "/workspace/sources"
          done
        fi

        find /workspace -type d
      env:
      - name: GH_TOKEN
        valueFrom:
          secretKeyRef:
            name: tip-git-basic-auth
            key: password