apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-ace-repos
spec:
  workspaces:
    - name: sources
  steps:
    - name: clone-each-repo-in-list
      image: quay.io/wire/alpine-git
      securityContext:
        privileged: true
        runAsUser: 0
      script: |
        #!/bin/sh
        apk add jq
        
        inputfile="/workspace/sources/repos.json"

        jq -cr '.[]' $inputfile | while read line; do
          echo "Cloning repo: $line ..."
          $(git clone https://github.com/andreas-bradahl/$line.git ./sources/repos/$line)
        done

        find /workspace