apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-and-deploy-integration-server
spec:
  params:
    - name: pod-name
    - name: namespace
  steps:

    - name: create-is-manifest
      image: image-registry.openshift-image-registry.svc:5000/cicd/origin-cli
      script: |
        echo "Creating IntegrationServer manifest"
        cat << EOF > integrationserver.yaml
        apiVersion: appconnect.ibm.com/v1beta1
        kind: IntegrationServer
        metadata:
          name: $(params.pod-name)
          labels:
            pod: $(params.pod-name)
          namespace: $(params.namespace)
        spec:
          license:
            accept: true
            license: L-APEH-BTHFYQ
            use: CloudPakForIntegrationNonProduction
          pod:
            containers:
              runtime:
                image: image-registry.openshift-image-registry.svc:5000/$(params.namespace)/$(params.pod-name)
                imagePullPolicy: Always
                resources:
                  limits:
                    cpu: 500m
                    memory: 500Mi
                  requests:
                    cpu: 300m
                    memory: 300Mi
          adminServerSecure: true
          router:
            timeout: 120s
          designerFlowsOperationMode: disabled
          service:
            endpointType: http
          version: 11.0.0.10-r3-eus
          replicas: 1
          barURL: ''
        EOF

        cat integrationserver.yaml

    - name: deploy-is-manifest
      image: image-registry.openshift-image-registry.svc:5000/cicd/origin-cli
      script: |
        echo "Applying IntegrationServer manifest to OpenShift cluster"
        oc apply -f integrationserver.yaml

    - name: wait-for-pod-readiness
      image: image-registry.openshift-image-registry.svc:5000/cicd/origin-cli
      script: |
        #!/bin/bash
        
        echo "Waiting for deployment to be created"

        POD_NAME=$(params.pod-name)
        SUFFIX='-is'
        echo "Looking for deployment with name ${POD_NAME}${SUFFIX}"

        timeout 10m bash -c "until oc get deployment.apps/${POD_NAME}${SUFFIX} &> /dev/null
        do
          echo . 
          sleep 2
        done"

        if [[ $(oc get deployment.apps/${POD_NAME}${SUFFIX}) ]]
        then
          echo "Deployment ${POD_NAME}${SUFFIX} found."
          echo "Waiting for deployment condition=Available."
          # Waits until pod is ready for traffic
          oc wait --for=condition=Available deployment/${POD_NAME}${SUFFIX} --timeout=90s
        else
          echo "Deployment ${POD_NAME}${SUFFIX} not found. Exiting..."
          exit 1
        fi
