apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fetch-dependent-repos
spec:
  workspaces:
  - name: source
  params:
    - name: topic-name
  steps:
    - name: fetch-dependent-repos
      image: python
      script: |
        #!/usr/bin/env python3
        python -m pip install --upgrade pip
        python -m pip install requests
        
        url = f"https://api.github.com/search/repositories?q=user:tineikt+topic:{$(params.topic-name)}"
        response = requests.get(url)
        print(response)

        repos = [value['name'] for value in response_dictionary['items']]
        print(repos)

        filename = 'repolist.json'
        os.makedirs(os.path.dirname(filename), exist_ok=True)

        with open(filename, 'w') as file:
          file.write(json.dumps(repos))